//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.RosterDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employment_basis
    {
        public int employment_basis_id { get; set; }
        public string employment_basis_desc { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
