//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.RosterDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RosterEntities : DbContext
    {
        public RosterEntities()
            : base("name=RosterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<roster> rosters { get; set; }
        public virtual DbSet<excel_export_header> excel_export_header { get; set; }
    
        public virtual ObjectResult<SP_EmployeeList_Result> SP_EmployeeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EmployeeList_Result>("SP_EmployeeList");
        }
    
        public virtual ObjectResult<SP_LoginUserDetails_Result> SP_LoginUserDetails(string loginEmailID)
        {
            var loginEmailIDParameter = loginEmailID != null ?
                new ObjectParameter("LoginEmailID", loginEmailID) :
                new ObjectParameter("LoginEmailID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LoginUserDetails_Result>("SP_LoginUserDetails", loginEmailIDParameter);
        }
    
        public virtual ObjectResult<SP_RoleList_Result> SP_RoleList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RoleList_Result>("SP_RoleList");
        }
    
        public virtual ObjectResult<SP_GetLoginDtsByRegisterUser_Result> SP_GetLoginDtsByRegisterUser(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetLoginDtsByRegisterUser_Result>("SP_GetLoginDtsByRegisterUser", iDParameter);
        }
    
        public virtual ObjectResult<SP_UserList_Result> SP_UserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserList_Result>("SP_UserList");
        }
    
        public virtual ObjectResult<SP_GetAllRosterDetails_Result> SP_GetAllRosterDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllRosterDetails_Result>("SP_GetAllRosterDetails");
        }
    
        public virtual ObjectResult<SP_GetEmployeeRosterDetails_Result> SP_GetEmployeeRosterDetails(Nullable<int> employee_Id)
        {
            var employee_IdParameter = employee_Id.HasValue ?
                new ObjectParameter("employee_Id", employee_Id) :
                new ObjectParameter("employee_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeeRosterDetails_Result>("SP_GetEmployeeRosterDetails", employee_IdParameter);
        }
    }
}
