//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.RosterDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_list
    {
        public int ID { get; set; }
        public string report_name { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public Nullable<bool> is_summary { get; set; }
    }
}
